basePath: /api
definitions:
  entities.AuthResponse:
    properties:
      access_token:
        type: string
      id:
        type: integer
      refresh_token:
        type: string
    type: object
  entities.ErrorEntity:
    properties:
      error:
        type: string
    type: object
  entities.LogoutTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  entities.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  entities.TokenPair:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  entities.UserCreateRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  entities.UserGet:
    properties:
      created_at:
        type: string
      id:
        type: integer
      login:
        type: string
    type: object
  entities.UserLoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  entities.UserUpdateLoginRequest:
    properties:
      id:
        type: integer
      login:
        type: string
    type: object
  entities.UserUpdateLoginResponse:
    properties:
      id:
        type: integer
    type: object
  entities.UserUpdatePasswordRequest:
    properties:
      id:
        type: integer
      password:
        type: string
    type: object
  entities.UserUpdatePasswordResponse:
    properties:
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger for IQJ test task.
  title: IQJ Test Task
  version: "1.0"
paths:
  /auth/logout:
    delete:
      consumes:
      - application/json
      description: Удаляет refresh токен
      parameters:
      - description: Refresh токен
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/entities.LogoutTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      security:
      - ApiKeyAuth: []
      summary: Удаление токена
      tags:
      - auth
  /auth/user/delete:
    delete:
      consumes:
      - application/json
      description: Удаляет пользователя из системы и отзывает все refresh токены
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      security:
      - ApiKeyAuth: []
      summary: Удаление пользователя
      tags:
      - auth
  /login:
    post:
      consumes:
      - application/json
      description: Вход в аккаунт пользователя, возвращает access и refresh токены
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: Вход в аккаунт пользователя
      tags:
      - auth
  /refresh:
    post:
      consumes:
      - application/json
      description: Обновляет access и refresh токены
      parameters:
      - description: Refresh токен
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/entities.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.TokenPair'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: Обновление токенов
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе и возвращает access и refresh
        токены
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: Создание пользователя
      tags:
      - auth
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: удаление пользователя
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: удаление пользователя
      tags:
      - users
    get:
      consumes:
      - application/json
      description: получаем пользователя по ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UserGet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: получение пользователя по ID
      tags:
      - users
  /user/all:
    get:
      consumes:
      - application/json
      description: получение всех пользователей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.UserGet'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: получение всех пользователей
      tags:
      - users
  /user/login:
    patch:
      consumes:
      - application/json
      description: обновление логина пользователя
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UserUpdateLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UserUpdateLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: обновление логина пользователя
      tags:
      - users
  /user/password:
    patch:
      consumes:
      - application/json
      description: обновление пароля пользователя
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UserUpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UserUpdatePasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: обновление пароля пользователя
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
