basePath: /api
host: localhost:8080
info:
  contact: {}
  description: IQJ test task.
  title: Swagger Example API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
