basePath: /api
definitions:
  entities.ErrorEntity:
    properties:
      error:
        type: string
    type: object
  entities.UserCreateRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  entities.UserCreateResponse:
    properties:
      id:
        type: integer
    type: object
  entities.UserGet:
    properties:
      created_at:
        type: string
      id:
        type: integer
      login:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger for IQJ test task.
  title: IQJ Test Task
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: получаем пользователя по ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.UserGet'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: получение пользователя по ID
      tags:
      - users
  /user/all:
    get:
      consumes:
      - application/json
      description: получение всех пользователей
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.UserGet'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: получение всех пользователей
      tags:
      - users
  /user/create:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.UserCreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.ErrorEntity'
      summary: Создание пользователя
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
